password reset + tests
wwi21seb-projekt/server-beta pull request #65
Opened 2024-05-25 14:14 UTC by linagrxth

## Checkliste für Reviewer
- [ ] Wurden die Variablen sprechend benannt?
- [ ] Wurden die Funktionen sprechend benannt?
- [ ] Sind Tests vorhanden?
- [ ] Ist der Code verständlich geschrieben?

2024-05-25 14:51 UTC, marcbudd requested changes
Der Code entspricht noch nicht genau den Spezifikationen in Postman. Außerdem wurden die Routen nicht in router.go hinzugefügt.
Die Tests habe ich mir noch nicht zu genau angesehen, weil ja noch einige Änderungen gemacht werden müssen. Aber wenn ich in die Fehlermeldungen gucke, sehe ich vor allem, dass die Custom Errors, die in den Tests erwartet werden, nicht mit den tatsächlichen übereinstimmen.
Mein Vorschlag: zuerst manuell mit Postman lokal testen, ob es funktioniert

2024-05-25 14:51 UTC, marcbudd commented on internal/models/password_reset.go
> +	Username       string    `gorm:"column:username;type:varchar(20);not_null"`
Fremdschlüsselbeziehung zum User fehlt (kannst du aus dem ActivationToken Model kopieren)

2024-05-25 14:51 UTC, marcbudd commented on internal/models/password_reset.go
> +}
Dieses DTO wird nicht benötigt, der Nutzername wird über die URL übergeben. Response DTO wird benötigt

2024-05-25 14:51 UTC, marcbudd commented on internal/services/password_reset_service.go
> +func (service *PasswordResetService) SetNewPassword(token string, newPassword string) (*customerrors.CustomError, int) {
Ich finde es hier eigentlich schöner, wenn du den gesamten req DTO übergibst und nicht nur die einzelnen Attribute, so wäre es auch konsistenter mit den anderen Funktionen, und schöner wenn noch mehr Attribute hinzukommen

2024-05-25 14:51 UTC, marcbudd commented on internal/services/password_reset_service.go
> +	}
- Das würde ich direkt nach dem validate new password block aufrufen
- zusätzlich musst du hier wie oben beim Token überprüfen, ob es ein ErrRecordNotFound Fehler ist, falls der User nicht existiert und dann NotFound zurückgeben
- (siehe Postman)

2024-05-25 14:51 UTC, marcbudd commented on internal/services/password_reset_service.go
> +	}
In Postman haben wir einfach nur Forbidden festgelegt, falls der Token nicht gefunden werden kann, falsch ist, abgelaufen ist, usw.
Außerdem fragst du nur allgemein nach dem Token und nicht, ob der Token dem Nutzer gehört. 
--> Daher in die Repo Funktion, in der SQL-Abfrage den Nutzernamen miteinbauen
--> Falls der Token nicht gefunden wurde oder abgelaufen ist, Forbidden zurückgeben

Auch die beiden verwendeten Custom Errors sind für den Activation Token und nicht den Passwort Reset Token, hier einen neuen Custom Error verwenden

2024-05-25 14:51 UTC, marcbudd commented on internal/controllers/password_reset_controller.go
> +	}
Der Request wurde in Postman anders definiert. Der Username wird aus der URL ausgelesen und das DTO fehlt nicht

2024-05-25 14:51 UTC, marcbudd commented on internal/services/password_reset_service.go
> +	return nil, http.StatusNoContent
Falsche Antwort: In Postman wurde 200 OK definiert mit einem Response Body, der eine zensierte Email enthält
also z. B. "mar*******@gmail.com"

2024-05-25 14:51 UTC, marcbudd commented on internal/controllers/password_reset_controller.go
> +
Der Nutzername muss aus der URL ausgelesen und an den Service übergeben werden

2024-05-25 14:51 UTC, marcbudd commented on internal/controllers/password_reset_controller_test.go
> +	assert.Equal(t, http.StatusNoContent, w.Code)
Mehr assertions

2024-05-25 14:53 UTC, marcbudd requested changes

2024-05-25 14:53 UTC, marcbudd commented on internal/repositories/password_reset_repository.go
> +}
Bitte nach ID und nicht nach Token löschen

2024-05-27 18:32 UTC, marcbudd approved these changes

2024-05-27 21:47 UTC, marcbudd approved these changes

2024-05-27 21:48 UTC, klarak04 approved these changes

2024-05-27 21:49 UTC, merged